ECommerceApp.UI/Models/CategoryListViewModel.cs
using ECommerce.Entities.Models;

namespace ECommerceApp.UI
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

ECommerceApp.UI/Models/ErrorViewModel.cs
namespace ECommerceApp.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerceApp.UI/Models/ProductListViewModel.cs
using ECommerce.Entities.Models;

namespace ECommerceApp.UI
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
        public int CurrentPage { get; internal set; }
        public int PageSize { get; internal set; }
        public int PageCount { get; internal set; }
        public int CurrentCategory { get; internal set; }
        public string CurrentProducts { get; internal set; }
        public string CurrentPrice { get; internal set; }
    }
}

ECommerceApp.UI/Controllers/HomeController.cs
using ECommerceApp.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerceApp.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerceApp.UI/Controllers/ProductController.cs
using ECommerce.Entities.Models;
using ECommerceApp.Business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceApp.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private static string oldSortName;
        private static string oldSortPrice;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int page = 1, int category = 0, string sortProducts = "asc", string sortPrice = "asc")
        {
            var items = await _productService.GetAllByCategoryId(category);
           
            
            if (oldSortName != sortProducts)
            {
                if (sortProducts == "asc")
                {
                    items = items.OrderBy(p => p.ProductName).ToList();
                }
                else
                {
                    items = items.OrderByDescending(p => p.ProductName).ToList();
                }
                oldSortName = sortProducts;
            }

            if (oldSortPrice != sortPrice)
            {
                if (sortPrice == "asc")
                {
                    items = items.OrderBy(p => p.UnitPrice).ToList();
                }
                else
                {
                    items = items.OrderByDescending(p => p.UnitPrice).ToList();
                }
                oldSortPrice = sortPrice;
            }

            if (oldSortName == "")
            {
                oldSortName = sortProducts;
            }
            if (oldSortPrice == "")
            {
                oldSortPrice = sortPrice;
            }


            var pageSize = 10;

            var model = new ProductListViewModel
            {
                Products = items.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                CurrentPage = page,
                PageSize = pageSize,
                PageCount = (int)Math.Ceiling(items.Count / (decimal)pageSize),
                CurrentCategory = category,
                CurrentProducts = sortProducts,
                CurrentPrice = sortPrice
            };

            return View(model);
        }
    }
}

ECommerceApp.UI/ViewComponents/CategoryListViewComponent.cs
using ECommerceApp.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ECommerceApp.UI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            var categories=await _categoryService.GetAllAsync();
            var param = HttpContext.Request.Query["category"];

            var category=int.TryParse(param, out var categoryId);

            var model = new CategoryListViewModel
            {
                Categories=categories,
                CurrentCategory=category ? categoryId : 0,
            };

            return View(model);
        }
    }
}

ECommerceApp.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerceApp.UI/Views/Product/Index.cshtml
<table class="table">
    <thead>
        <tr>
            <th>
                Product Name
                <a class="btn btn-primary"
                   asp-action="Index"
                   asp-route-page="@Model.CurrentPage"
                   asp-route-category="@Model.CurrentCategory"
                   asp-route-sortProducts="@(Model.CurrentProducts == "asc" ? "desc" : "asc")"
                   asp-route-sortPrice="@Model.CurrentPrice">
                    @(Model.CurrentProducts == "asc" ? "A to Z" : "Z to A")
                </a>
            </th>
            <th>
                Unit Price
                <a class="btn btn-primary"
                   asp-action="Index"
                   asp-route-page="@Model.CurrentPage"
                   asp-route-category="@Model.CurrentCategory"
                   asp-route-sortProducts="@Model.CurrentProducts"
                   asp-route-sortPrice="@(Model.CurrentPrice == "asc" ? "desc" : "asc")">
                    @(Model.CurrentPrice == "asc" ? "Lower to Higher" : "Higher to Lower")
                </a>
            </th>
            <th>Unit In Stock</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>$@item.UnitPrice</td>
                <td>@item.UnitsInStock</td>
                <td>
                    <a class="btn btn-xs btn-success">
                        Add To Cart
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>


<div>
    @if (Model.CurrentPage > 1)
    {
        <a class="btn btn-primary" 
           asp-action="Index"
           asp-route-page="@(Model.CurrentPage - 1)"
           asp-route-category="@Model.CurrentCategory"
           asp-route-sortProducts="@Model.CurrentProducts"
           asp-route-sortPrice="@Model.CurrentPrice">Prev</a>
    }

    @for (int i = 1; i <= Model.PageCount; i++)
    {
        <a class="btn btn-success @(i == Model.CurrentPage ? "active" : "")"
           asp-action="Index"
           asp-route-page="@i"
           asp-route-category="@Model.CurrentCategory"
           asp-route-sortProducts="@Model.CurrentProducts"
           asp-route-sortPrice="@Model.CurrentPrice">@i</a>
    }

    @if (Model.CurrentPage < Model.PageCount)
    {
        <a class="btn btn-primary" asp-action="Index"
           asp-route-page="@(Model.CurrentPage + 1)"
           asp-route-category="@Model.CurrentCategory"
           asp-route-sortProducts="@Model.CurrentProducts"
           asp-route-sortPrice="@Model.CurrentPrice">Next</a>
    }
</div>

ECommerceApp.UI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel
<section class="list-group">
    @if(Model.CurrentCategory == 0)
    {
        <a class="list-group-item active" style=" cursor:pointer;" href="/product/index?category=0">All Categories</a>
    }
    else
    {
        <a class="list-group-item " style=" cursor:pointer;" href="/product/index?category=0">All Categories</a>
    }

    @foreach (var item in Model.Categories)
    {
        var css = "list-group-item";
        @if (item.CategoryId == Model.CurrentCategory)
        {
            css += " active";
        }

        <a class="@css" style="cursor:pointer;"
           href="/product/index?category=@item.CategoryId">@item.CategoryName</a>

    }
</section>

ECommerceApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerceApp.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerceApp.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerceApp.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <section class="row">
            <div class="col-md-2">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <div class="col-md-10">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </section>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ECommerceApp.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>